[package]
name = "vote"
version = "0.0.1"
authors = ["Benoit Frauly <benoit.frauly@outlook.com>"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"
[dependencies.multiversx-sc]
version = "0.39.5"

[dev-dependencies.multiversx-sc-scenario]
version = "0.39.5"
